# Generated by Django 2.2.4 on 2019-08-20 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title for snippet of code', max_length=200)),
                ('languages', models.CharField(choices=[('python', 'python'), ('js', 'js'), ('html', 'html'), ('lua', 'lua'), ('css', 'css'), ('clike', 'clike'), ('markup', 'markup'), ('html', 'html'), ('bash', 'bash'), ('django', 'django'), ('go', 'go'), ('json', 'json'), ('http', 'http'), ('php', 'php'), ('ruby', 'ruby'), ('sas', 'sas'), ('sass', 'sass'), ('scss', 'scss'), ('sql', 'sql')], default='html', max_length=7)),
                ('code', models.TextField(help_text='Enter the snippet code')),
                ('description', models.TextField(blank=True, help_text='Enter a docstring to describe the snippet of code.', max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copied_at', models.DateTimeField(auto_now_add=True)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Snippet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-copied_at'],
            },
        ),
        migrations.AddField(
            model_name='snippet',
            name='copy_snippet',
            field=models.ManyToManyField(help_text='Click to add snippet to user page.', related_name='LoggedIn', through='core.UserPage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snippet',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
